[package]
name = "adventofcode-2016"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_lib_rust = { path = "../aoc_lib_rust" }
